"""
Full pipeline debug runner — all datasets.
Runs: profile → score → build_recommendations → LLM 1 (enrich) → LLM 2 (transform_code) → apply.

Each dataset gets a log file in logs/<dataset>.log with:
  - data sample
  - profile stats per column
  - baseline recommendations JSON
  - LLM system prompt
  - LLM user prompt (full, including profile CSV and baseline JSON)
  - LLM raw response
  - post-processing guards applied
  - final enriched recommendations JSON
  - transform_hints found by LLM 1 + lambdas generated by LLM 2
  - before/after score comparison

Run: .venv/bin/python3 test_pipeline.py
"""

import json
import logging
import os
import sys
import time
from pathlib import Path

# Load .env before importing anything
for line in open(".env"):
    line = line.strip()
    if line and not line.startswith("#") and "=" in line:
        k, v = line.split("=", 1)
        os.environ.setdefault(k.strip(), v.strip())

import pandas as pd

sys.path.insert(0, "prefect")
from flows.dq_logic import (
    apply_recommendations,
    build_recommendations,
    profile_dataframe,
    score_profile_detailed,
)
from flows.llm_enrichment import (
    _build_llm_profile,
    _RUNNER_SYSTEM,
    _TRANSFORM_SYSTEM,
    enrich_recommendations,
    generate_transform_code,
)

DATASETS = [
    "test_data/ecomm_orders_small.csv",
    "test_data/finance_txn_medium.csv",
    "test_data/medical_labs_medium.csv",
    "test_data/retail_catalog_wide.csv",
    "test_data/iot_sensors_large.csv",
    "test_data/crm_contacts_xlarge.csv",
]

LOGS_DIR = Path("logs")
LOGS_DIR.mkdir(exist_ok=True)

BOX_W = 76


# ---------------------------------------------------------------------------
# Logger setup — writes full debug output to file, INFO to console
# ---------------------------------------------------------------------------

class SectionFileHandler(logging.FileHandler):
    """
    File handler that intercepts DEBUG messages beginning with LLM_ and
    formats them as titled boxes in the log file.
    """
    def emit(self, record: logging.LogRecord) -> None:
        if record.levelno == logging.DEBUG and record.getMessage().startswith("LLM_"):
            msg = record.getMessage()
            # first line is the title (e.g. "LLM_SYSTEM_PROMPT")
            lines = msg.split("\n", 1)
            title = lines[0].replace("_", " ")
            body = lines[1] if len(lines) > 1 else ""
            border = "─" * BOX_W
            formatted = f"\n┌─ {title} {'─' * max(0, BOX_W - len(title) - 3)}┐\n"
            for l in body.splitlines():
                formatted += f"│ {l}\n"
            formatted += f"└{border}┘\n"
            try:
                self.stream.write(formatted)
                self.stream.flush()
            except Exception:
                self.handleError(record)
        else:
            super().emit(record)


def make_logger(name: str, log_path: Path) -> tuple[logging.Logger, SectionFileHandler]:
    logger = logging.getLogger(name)
    logger.setLevel(logging.DEBUG)
    logger.handlers.clear()
    logger.propagate = False

    fmt = logging.Formatter("%(asctime)s  %(levelname)-8s  %(message)s", datefmt="%H:%M:%S")

    # Console — INFO and above only
    ch = logging.StreamHandler(sys.stdout)
    ch.setLevel(logging.INFO)
    ch.setFormatter(fmt)
    logger.addHandler(ch)

    # File — everything including DEBUG (LLM prompts / responses)
    fh = SectionFileHandler(log_path, mode="w", encoding="utf-8")
    fh.setLevel(logging.DEBUG)
    fh.setFormatter(fmt)
    logger.addHandler(fh)

    return logger, fh


def attach_llm_logger(fh: SectionFileHandler) -> None:
    """
    Share the dataset's file handler with the llm_enrichment module logger
    so LLM prompts and responses land in the same file in the correct order.
    Using the same handler instance guarantees a single file descriptor — no ordering issues.
    """
    llm_log = logging.getLogger("flows.llm_enrichment")
    llm_log.setLevel(logging.DEBUG)
    llm_log.handlers.clear()
    llm_log.propagate = False
    llm_log.addHandler(fh)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def section(log, title: str) -> None:
    log.info("─" * BOX_W)
    log.info(f"  {title}")
    log.info("─" * BOX_W)


def fmt_score(s: dict) -> str:
    return (
        f"overall={s['overall']:.1f}  "
        f"C={s['completeness']:.1f}  "
        f"U={s['uniqueness']:.1f}  "
        f"V={s['validity']:.1f}  "
        f"Cn={s['consistency']:.1f}"
    )


def log_df_sample(log, df: pd.DataFrame, n: int = 10) -> None:
    """Print a readable sample of the raw data."""
    sample = df.head(n).fillna("<null>")
    log.info(f"  data sample (first {min(n, len(df))} rows):")
    # header
    cols = list(df.columns)
    widths = [max(len(c), 8) for c in cols]
    header = "  " + "  ".join(c.ljust(w) for c, w in zip(cols, widths))
    log.info(header)
    log.info("  " + "  ".join("-" * w for w in widths))
    for _, row in sample.iterrows():
        line = "  " + "  ".join(str(v)[:w].ljust(w) for v, w in zip(row, widths))
        log.info(line)


def log_profile_table(log, profile: dict) -> None:
    """Print per-column profile facts."""
    log.info("  column profile:")
    hdr = f"  {'column':<22} {'type':<8} {'null%':>6}  {'strategy hint':>14}  {'outliers':>8}  {'sentinel':>8}  {'stats'}"
    log.info(hdr)
    log.info("  " + "─" * (BOX_W - 2))
    for col, cp in profile.get("column_profiles", {}).items():
        dtype = cp.get("detected_type", "?")
        null_pct = cp.get("null_pct", 0)
        sentinel = cp.get("sentinel_count", 0)
        outliers = cp.get("outliers", {}).get("count", 0)
        s = cp.get("stats", {})
        if s.get("mean") is not None:
            stats_str = f"mean={s['mean']}  median={s['median']}  min={s['min']}  max={s['max']}"
        elif s.get("min"):
            stats_str = f"min={s['min']}  max={s['max']}"
        else:
            stats_str = ""
        log.info(
            f"  {col:<22} {dtype:<8} {null_pct:>5.1f}%  {'':>14}  {outliers:>8}  {sentinel:>8}  {stats_str}"
        )


def log_recs_json(log, label: str, recs: dict) -> None:
    log.info(f"  {label}:")
    for line in json.dumps(recs, indent=2, default=str).splitlines():
        log.info(f"    {line}")


def log_diff(log, base: dict, enriched: dict) -> None:
    changes = []
    for col, ecd in enriched.get("columns", {}).items():
        bcd = base.get("columns", {}).get(col, {})
        col_changes = []
        for key in ("type", "missing_values", "normalize", "rename_to", "transform_hint", "transform_code", "note"):
            bval = bcd.get(key)
            eval_ = ecd.get(key)
            if bval != eval_ and eval_ is not None:
                if key == "missing_values":
                    bs = bval["strategy"] if isinstance(bval, dict) else str(bval)
                    es = eval_["strategy"] if isinstance(eval_, dict) else str(eval_)
                    if bs != es:
                        col_changes.append(f"strategy: {bs!r} → {es!r}")
                elif key == "note":
                    col_changes.append(f"note: {str(eval_)[:100]}")
                elif key == "rename_to":
                    col_changes.append(f"rename_to: {eval_!r}")
                else:
                    col_changes.append(f"{key}: {bval!r} → {eval_!r}")
        if col_changes:
            changes.append((col, col_changes))

    if not changes:
        log.info("  LLM changes: none — baseline kept as-is")
        return

    log.info(f"  LLM changes ({sum(len(c) for _, c in changes)} field(s) across {len(changes)} column(s)):")
    for col, col_changes in changes:
        log.info(f"    {col}:")
        for c in col_changes:
            log.info(f"      {c}")


# ---------------------------------------------------------------------------
# Main per-dataset runner
# ---------------------------------------------------------------------------

def run_dataset(path: str) -> None:
    from datetime import date
    dataset_name = Path(path).stem
    log_path = LOGS_DIR / f"{dataset_name}_{date.today().isoformat()}.log"
    log, fh = make_logger(dataset_name, log_path)
    attach_llm_logger(fh)

    # ── 1. LOAD ───────────────────────────────────────────────────────────
    section(log, f"1. LOAD  ·  {path}")
    t0 = time.perf_counter()
    df = pd.read_csv(path)
    log.info(f"  {df.shape[0]} rows × {df.shape[1]} cols  ({time.perf_counter()-t0:.3f}s)")
    log.info(f"  columns: {list(df.columns)}")
    log.info(f"  dtypes:  {dict(df.dtypes.astype(str))}")
    null_counts = df.isnull().sum()
    non_zero_nulls = {c: int(v) for c, v in null_counts.items() if v > 0}
    if non_zero_nulls:
        log.info(f"  nulls:   {non_zero_nulls}")

    log_df_sample(log, df)

    # ── 2. PROFILE ────────────────────────────────────────────────────────
    section(log, "2. PROFILE")
    t0 = time.perf_counter()
    profile = profile_dataframe(df)
    elapsed = time.perf_counter() - t0
    log.info(
        f"  done ({elapsed:.3f}s)  "
        f"completeness={profile['completeness']:.1f}%  "
        f"uniqueness={profile['uniqueness']:.1f}%  "
        f"validity={profile['validity']:.1f}%  "
        f"consistency={profile['consistency']:.1f}%"
    )
    log_profile_table(log, profile)

    # ── 3. SCORE (before) ─────────────────────────────────────────────────
    section(log, "3. DQ SCORE — BEFORE")
    score_before = score_profile_detailed(profile)
    log.info(f"  {fmt_score(score_before)}")

    # ── 4. BASELINE RECOMMENDATIONS ───────────────────────────────────────
    section(log, "4. BASELINE RECOMMENDATIONS")
    t0 = time.perf_counter()
    base_recs = build_recommendations(df, profile, score_before["overall"])
    elapsed = time.perf_counter() - t0
    issues = base_recs.get("_metadata", {}).get("issues_found", {})
    non_empty = {k: v for k, v in issues.items() if v}
    log.info(f"  generated ({elapsed:.3f}s)")
    if non_empty:
        log.info(f"  issues found: {non_empty}")
    log_recs_json(log, "baseline recommendations", base_recs)

    # ── 5. LLM PROFILE (what goes into the prompt) ────────────────────────
    section(log, "5. LLM PROFILE  (sent to LLM as context)")
    llm_profile_str = _build_llm_profile(profile, df)
    for line in llm_profile_str.splitlines():
        log.info(f"  {line}")

    # ── 6. LLM SYSTEM PROMPT ──────────────────────────────────────────────
    section(log, "6. LLM SYSTEM PROMPT")
    for line in _RUNNER_SYSTEM.splitlines():
        log.info(f"  {line}")

    # ── 7. LLM ENRICHMENT (prompt + response logged at DEBUG by llm_enrichment) ──
    section(log, "7. LLM ENRICHMENT  (LLM 1)")
    log.info("  calling enrich_recommendations()  →  see LLM_USER_PROMPT and LLM_RESPONSE below in file")
    t0 = time.perf_counter()
    enriched_recs = enrich_recommendations(profile, base_recs, df)
    elapsed = time.perf_counter() - t0
    n_notes = sum(1 for cd in enriched_recs.get("columns", {}).values() if cd.get("note"))
    n_renames = sum(1 for cd in enriched_recs.get("columns", {}).values() if cd.get("rename_to"))
    n_hints = sum(1 for cd in enriched_recs.get("columns", {}).values() if cd.get("transform_hint"))
    log.info(f"  done ({elapsed:.3f}s)  notes={n_notes}  renames={n_renames}  transform_hints={n_hints}")

    # ── 8. TRANSFORM CODE GENERATION  (LLM 2) ────────────────────────────
    section(log, "8. TRANSFORM SYSTEM PROMPT  (LLM 2)")
    for line in _TRANSFORM_SYSTEM.splitlines():
        log.info(f"  {line}")

    section(log, "8b. GENERATE TRANSFORM CODE  (LLM 2)")
    hints = {
        col: cd["transform_hint"]
        for col, cd in enriched_recs.get("columns", {}).items()
        if cd.get("transform_hint")
    }
    if hints:
        log.info(f"  {len(hints)} column(s) with transform_hint from LLM 1:")
        for col, hint in hints.items():
            log.info(f"    {col}: {hint}")
    else:
        log.info("  no columns have transform_hint — LLM 1 found no per-cell value issues")

    t0 = time.perf_counter()
    final_recs = generate_transform_code(enriched_recs, df)
    elapsed = time.perf_counter() - t0

    codes = {
        col: cd["transform_code"]
        for col, cd in final_recs.get("columns", {}).items()
        if cd.get("transform_code")
    }
    failed = [col for col in hints if col not in codes]
    log.info(f"  done ({elapsed:.3f}s)  {len(codes)}/{len(hints)} column(s) got transform_code")
    for col, code in codes.items():
        log.info(f"    {col}: {code}")
    if failed:
        log.info(f"  all 3 attempts failed (skipped): {failed}")

    # ── 9. LLM DIFF ───────────────────────────────────────────────────────
    section(log, "9. ALL LLM CHANGES vs BASELINE  (LLM 1 + LLM 2)")
    log_diff(log, base_recs, final_recs)

    # ── 10. FINAL RECOMMENDATIONS ─────────────────────────────────────────
    section(log, "10. FINAL RECOMMENDATIONS  (stored in DB for user review)")
    log_recs_json(log, "final recommendations", final_recs)

    # ── 11. APPLY ─────────────────────────────────────────────────────────
    section(log, "11. APPLY RECOMMENDATIONS")
    t0 = time.perf_counter()
    cleaned = apply_recommendations(df.copy(), final_recs)
    elapsed = time.perf_counter() - t0
    rows_dropped = df.shape[0] - cleaned.shape[0]
    cols_dropped = df.shape[1] - cleaned.shape[1]
    log.info(f"  done ({elapsed:.3f}s)  {df.shape[0]}×{df.shape[1]} → {cleaned.shape[0]}×{cleaned.shape[1]}")
    if rows_dropped:
        log.info(f"  rows dropped: {rows_dropped}")
    if cols_dropped:
        log.info(f"  cols dropped: {cols_dropped}")

    # ── 12. SCORE (after) ─────────────────────────────────────────────────
    section(log, "12. DQ SCORE — AFTER")
    score_after = score_profile_detailed(profile_dataframe(cleaned))
    delta = score_after["overall"] - score_before["overall"]
    log.info(f"  before : {fmt_score(score_before)}")
    log.info(f"  after  : {fmt_score(score_after)}")
    log.info(f"  delta  : {delta:+.2f}")

    log.info("")
    log.info(f"  LOG SAVED → {log_path}")


# ---------------------------------------------------------------------------
# Run all datasets
# ---------------------------------------------------------------------------

summary = []
errors = []

for path in DATASETS:
    print(f"\n{'═' * BOX_W}")
    print(f"  DATASET: {path}")
    print(f"{'═' * BOX_W}")
    try:
        run_dataset(path)
        summary.append(f"  PASS  {path}")
    except Exception as e:
        import traceback
        errors.append((path, e))
        summary.append(f"  FAIL  {path}  — {e}")
        print(f"\n  !! ERROR: {e}")
        traceback.print_exc()

print(f"\n{'═' * BOX_W}")
print("  SUMMARY")
print(f"{'═' * BOX_W}")
for line in summary:
    print(line)
print(f"{'─' * BOX_W}")
if errors:
    print(f"  {len(errors)} failure(s). Check logs/ for details.")
else:
    print(f"  All {len(DATASETS)} datasets passed.")
    print(f"  Full debug logs (prompts, responses, JSON) → logs/<dataset>_<date>.log")
print(f"{'═' * BOX_W}")
